resources:
  - name: version
    public: true
    type: semver
    source:
      driver: git
      uri: git@github.com:zankich/concourse-scratch
      branch: master
      file: version
      private_key: {{private-repo-key}}
  - name: code
    public: true
    type: git
    source:
      uri: https://github.com/zankich/concourse-scratch
      branch: master
jobs:
  - name: client1
    public: true
    plan:
      - get: code
        trigger: true
      - task: build
        file: code/ci/client1.yml
  - name: client2
    public: true
    plan:
      - get: code
        trigger: true
      - task: build
        file: code/ci/client2.yml
  - name: main
    public: true
    plan:
      - get: code
        trigger: true
        passed: [client1, client2]
      - task: build
        file: code/ci/main.yml
  - name: rc
    public: true
    plan:
      - get: code
        trigger: true
        passed: [main]
      - get: version
        params: {pre: rc}
      - put: version
        params: {file: version/number}
