resources:
  - name: code
    type: git
    source:
      uri: https://github.com/zankich/concourse-scratch
      branch: master
jobs:
  - name: client1
    plan:
      - get: code
        trigger: true
      - task: build
        file: code/ci/client1.yml
  - name: client2
    plan:
      - get: code
        trigger: true
      - task: build
        file: code/ci/client2.yml
  - name: main
    plan:
      - get: code
        trigger: true
        passed: [client1, client2]
      - task: build
        file: code/ci/main.yml
